### ISSUE TITLE
Store Support

### ISSUE THREAD

**Issue by chr-hertel** [php-llm/llm-chain#29]
Following stores would be interesting:

- [ ] Redis
- [ ] Elastic
- [ ] Postgres
- [ ] MySQL
- [x] Pinecone (#55)
- [ ] Cosmo
- [ ] Qdrant
- [ ] Milvus
- [ ] Gally
- [x] MongoDB (#42)
- [ ] [Weaviate](https://weaviate.io)
- [ ] InMemory

And more?

**Comment by OskarStark** [comment]
Gally

**Comment by chr-hertel** [comment]
Closed in favor of #28
